version: "3.7"

volumes:
    mysql-data:

services:
  app:
    build:
      args:
        user: ${USER}
        uid: ${UID}
      context: ./
      dockerfile: Dockerfile
    image: laravel-login
    container_name: laravel-login-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-login
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_ROOT}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER_ROOT=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=America/Sao_Paulo
    networks:
      - laravel-login
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: laravel-login-nginx
    restart: unless-stopped
    ports:
      - 6001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel-login
    links:
      - db:db
    depends_on:
      - app
      - db

networks:
  laravel-login:
    driver: bridge
